### ISSUE TITLE
Lazy imports for {napari,Qt}-related packages?

### ISSUE THREAD

**Issue by tcompa** [haesleinhuepf/napari-skimage-regionprops#36]
Hi there,

Together with @jluethi and others we implemented a wrapper of `napari-workflows` to be run within the Fractal system (the current -experimental- version of the wrapper is [this one](https://github.com/fractal-analytics-platform/fractal-tasks-core/blob/main/fractal_tasks_core/napari_workflows_wrapper.py)). In our current workflows, we already use `napari-skimage-regionprops` and `napari-segment_blobs-and-things-with-membranes`.

Since we execute the workflows as part of HPC jobs, we do not need all features related to napari or the graphical interface, and we would appreciate if those dependencies were optional. This is not the case at the moment, since running a workflow without `qtpy` available fails with a `ModuleNotFoundError` (the `__init__.py` of this package imports `_table.py`, which in turn imports from `qtpy.QtCore`). This is also true for `napari-segment-blobs-and-things-with-membranes`.

In the same spirit as releases 0.2.7 and 0.2.8 of `napari-workflows`, would it be possible to make some graphics-related dependencies optional, by moving the related import statements within the functions that actually need them? I'm not sure I can write a PR myself, but I'd be glad to test any proposed update.

Cheers, Tommaso

**Comment by haesleinhuepf** [comment]
Hi @tcompa ,

> Since we execute the workflows as part of HPC jobs

We have a very similar scenario here! 🙌 




> This is not the case at the moment, since running a workflow without `qtpy` available fails with a `ModuleNotFoundError` (the `__init__.py` of this package imports `_table.py`, which in turn imports from `qtpy.QtCore`). This is also true for `napari-segment-blobs-and-things-with-membranes`.

You are referring to these places:
* https://github.com/haesleinhuepf/napari-skimage-regionprops/blob/15300b28f7a9ae1a12be2e9b04f748c06c180c3b/napari_skimage_regionprops/_table.py#L5
* In napari-segment-blobs-and-things-with-membranes, I'm not sure where to find the import that hurts your use-case. https://github.com/haesleinhuepf/napari-segment-blobs-and-things-with-membranes/blob/main/napari_segment_blobs_and_things_with_membranes/__init__.py

So yes, PRs are welcome! Otherwise, I can also fix it, just point me to all the places you discover that cause these issues. I just fixed some and hopefully soon all my/our napari plugins will work nicely headless on HPC.

Thanks for the feedback btw!

Best,
Robert

**Comment by tcompa** [comment]
Yes, I'm referring to that `from qtpy.QtCore import QTimer` import. And the same problem holds for `qtpy.QtWidgets` (next line) and for `napari_tools_menu`.

> In napari-segment-blobs-and-things-with-membranes, I'm not sure where to find the import that hurts your use-case. 

It's the import of `napari_tools_menu`, which then imports `QMenu` and `QTimer` (and probably other "offending" ones as well).

Thanks.

**Comment by jluethi** [comment]
Thanks @haesleinhuepf !

> I just fixed some and hopefully soon all my/our napari plugins will work nicely headless on HPC

At least for our use cases, running in headless mode hasn't been an issue, even with those imports. But the chance to reduce dependencies and have environments without Qt is attractive to us :)

**Comment by haesleinhuepf** [comment]
> But the chance to reduce dependencies and have environments without Qt is attractive to us :)

Yes, fully agreed. Let's make this happen!

**Comment by tcompa** [comment]
>  If you send a PR, cool.

Would you expect a try/except block like the one below?
```python
try:
    import napari._qt
except:
    warnings.warn("importing napari._qt failed")
    pass
```

In that case, I can add a few of those (there would be at least one for `qtpy` and one for `napari_tool_menu`, plus maybe others).

**Comment by haesleinhuepf** [comment]
> Would you expect a try/except block like the one below?

Yes, that would be great! Just to demonstrate something, I did that [here](https://github.com/haesleinhuepf/napari-tools-menu/pull/9/commits/1ba4ac2a56828fb1a54046430cfc89cbde9a187b) and I wanted to show you a better alternative; which is not always possible: delayed imports; [importing napari/qt things inside a function/class](https://github.com/haesleinhuepf/napari-tools-menu/pull/9/commits/25d61ecacfd89a330f50e8adb9ee7a009255fe0e). That's better than try-except blocks.

Thanks so much for your support!

**Comment by tcompa** [comment]
Closed with https://github.com/haesleinhuepf/napari-skimage-regionprops/pull/51 (@haesleinhuepf thanks for the rapid merge&release!)

For the record, it now works as expected:
```
$ pip show napari-tools-menu
Name: napari-tools-menu
Version: 0.1.19
[...]
Requires: napari, napari-plugin-engine, numpy
Required-by: napari-skimage-regionprops

$ pip show napari-skimage-regionprops
Name: napari-skimage-regionprops
Version: 0.8.1
[...]
Requires: imageio, napari, napari-plugin-engine, napari-tools-menu, napari-workflows, numpy, pandas, scikit-image
Required-by: 

$ python

Python 3.9.0 (default, Nov 15 2020, 14:28:56) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import napari_tools_menu
/home/tommaso/miniconda3/envs/test/lib/python3.9/site-packages/napari_tools_menu/__init__.py:10: UserWarning: Importing QT failed; now introducing dummy definitions of QMenu class and register_function decorator.
  warnings.warn("Importing QT failed; now introducing dummy definitions of QMenu class and register_function decorator.")
/home/tommaso/miniconda3/envs/test/lib/python3.9/site-packages/napari_tools_menu/__init__.py:221: UserWarning: Error in monkey patching napari. Please let @haesleinleinhuepf know at
https://github.com/haesleinhuepf/napari-tools-menu/issues
  warnings.warn("Error in monkey patching napari. Please let @haesleinleinhuepf know at\nhttps://github.com/haesleinhuepf/napari-tools-menu/issues")

>>> import napari_skimage_regionprops
/home/tommaso/miniconda3/envs/test/lib/python3.9/site-packages/napari_skimage_regionprops/_table.py:7: UserWarning: No Qt bindings could be found
  warnings.warn(str(e))

>>> napari_skimage_regionprops.__version__
'0.8.1'
```
