### ISSUE TITLE
automatically detect image dimension (2D/3D) for supported properties

### ISSUE THREAD

**Issue by chili-chiu** [haesleinhuepf/napari-skimage-regionprops#4]
Some skimage.measure.regionprops are not yet supporting 3D analysis, and running the plugin on 3D labels can sometimes cause NotImplementedError.

**Comment by haesleinhuepf** [comment]
Hi @chili-chiu ,

thanks for reporting!

Just as a workaround: If you run it with this configuration, it will run:
![image](https://user-images.githubusercontent.com/12660498/133888413-662922f9-aa86-4ecb-bc2d-ed49b90b02c5.png)

I'm also [linking a related issue](https://github.com/scikit-image/scikit-image/issues/3812) in scikit-image.
