### ISSUE TITLE
Extraneous print commands

### ISSUE THREAD

**Issue by zoccoler** [haesleinhuepf/napari-skimage-regionprops#54]
Hi Robert @haesleinhuepf ,

I am running napari-skimage-regionprops from a notebook in a for loop and I have been getting a lot of print statements.

Is [this line](https://github.com/haesleinhuepf/napari-skimage-regionprops/blob/5d0315cbe5bdfda976cd58c17c4ea69c485e87a6/napari_skimage_regionprops/_regionprops.py#L114) there for a reason or by accident? If it is the latter, can we remove it?

Thanks!

**Comment by haesleinhuepf** [comment]
Sorry, that's an accident @zoccoler. Feel free to send a PR or I'll take care of it soon.

**Comment by zoccoler** [comment]
Sure, just did it.
