### ISSUE TITLE
measure things inside things doesn't do anything with default settings

### ISSUE THREAD

**Issue by haesleinhuepf** [haesleinhuepf/napari-skimage-regionprops#56]
Hi Marcelo @zoccoler ,

I was just testing your new `Measure things inside things` menu (note: I renamed it a little bit). Unfortunately, it doesn't show any result with the default settings.

To reproduce:
* Install devbio-napari + the master branch of this repository
* Start Napari
* Open Samples > clesperanto > Blobs
* Tools > Segmentation / Labeling > Gauss-Otsu-Labeling
* Tools > Measurement tables > Measure things inside things
* Click `Run`
No table opens :-(

Would you mind taking a look?

Thanks!

**Comment by haesleinhuepf** [comment]
Hi Marcelo @zoccoler ,

I can fix the issue by setting `things_inside_things = False` here: 
https://github.com/haesleinhuepf/napari-skimage-regionprops/blob/88046c63747d38f745f7af568938968f8b0575e5/napari_skimage_regionprops/_multichannel.py#L151

The problem in my case was, I only have a label image selected as reference, and there is nothing to measure inside. Furthermore, this warning is not displayed on my screen:
https://github.com/haesleinhuepf/napari-skimage-regionprops/blob/88046c63747d38f745f7af568938968f8b0575e5/napari_skimage_regionprops/_multichannel.py#L325-L326

... even though it runs into this block. (I put a print statement there). I'm working with napari 0.4.17... is it possible that it doesn't show warnings anymore??

**Comment by zoccoler** [comment]
Hi Robert @haesleinhuepf ,

Thanks for noticing and raising this issue! I can replicate this behavior. I am working on fixing it by using [napari notifications](https://napari.org/dev/api/napari.utils.notifications.html).

**Comment by haesleinhuepf** [comment]
Still doesn't work...

**Comment by haesleinhuepf** [comment]
Done in #62
