### ISSUE TITLE
wrong values for table generated images

### ISSUE THREAD

**Issue by romainGuiet** [haesleinhuepf/napari-skimage-regionprops#59]
Hi @haesleinhuepf ,

 I would like to measure object intensities

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/8309560/221752754-640cb2c3-840d-4615-895b-58775a322a4d.png">

but the generated image (double clicking on the header) does not reflect these values

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/8309560/221752273-48dc4b0e-9ddb-488a-ac14-8209933b80ce.png">

when I "mouse over" objects, the value is almost all the time 1.14 e03, even for the one to be 36216 (background is 0 ).
What's weird is that the contrast limit, max is 36216 and "compressing" limits doesn't improve the visualisation of the results

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/8309560/221753705-82b8cf9a-fcde-4416-bff9-bc74be8e3997.png">

I generated an image using the column index , and it seems a lot of labels have the same display value 6.49e04 (while values are different in the table) :
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/8309560/221755107-95acd1e5-0426-4368-8308-03aa1f7f88a7.png">

Similar data (I reproduced the issue but didn't redo all the screenshots ) can be found [on zenodo , Crop_ds441.tif ](https://zenodo.org/record/6645978#.Y_2DT3bMLtU).

Best

Romain

**Comment by haesleinhuepf** [comment]
I presume this happens because the labels are not ordered in the table (the index column appears not sequencially increasing). Thus, finally a reason to fix #48 

Question @romainGuiet : How were the segmentation and the measurements/ table made?
