### ISSUE TITLE
Save as csv/copy to clipboard not working

### ISSUE THREAD

**Issue by lazigu** [haesleinhuepf/napari-skimage-regionprops#6]
Hi @haesleinhuepf,

When trying to save/copy measurements error is received:
_AttributeError: 'QTableWidget' object has no attribute 'to_dataframe'_

I noticed because it stopped working in my plugin but did not fix it yet, maybe you will be faster.

**Comment by lazigu** [comment]
Hi Robert @haesleinhuepf,

works like a charm now!

**Comment by haesleinhuepf** [comment]
Thanks for testing and thanks again for reporting!
