### ISSUE TITLE
RegionProps are only measured for the "big" background object (pixel = 0) instead of measuring the labels?

### ISSUE THREAD

**Issue by sebi06** [haesleinhuepf/napari-skimage-regionprops#8]
Hi,

I added labels to my image ontop of the original image and wanted to measure their properties. The labels all have the pixel value = 1 and the rest = 0. But the measurement only shows one result for the background (=0). Any idea, why regionprops is measuring the "one bug background object" instead of all the segmented cell nuclei?

<img width="1485" alt="image" src="https://user-images.githubusercontent.com/3833249/146771594-f37ccb90-ea0d-4d8a-92e5-321ede759317.png">

**Comment by sebi06** [comment]
Nevermind ... :-) I found the issue. I just forgot the call the skimage "label" function before adding the objects.

<img width="1485" alt="image" src="https://user-images.githubusercontent.com/3833249/146772661-ecd1c185-96e5-469e-b425-c0ef0cb817ab.png">

**Comment by haesleinhuepf** [comment]
Thanks @sebi06! Better report one bug too much anymore than one too less. Looking forward to your czi dnn plugin release! 🌞
